# Generated by Django 5.1.5 on 2025-02-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_email', models.CharField(max_length=30)),
                ('admin_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wastetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=30)),
                ('worker_email', models.CharField(max_length=30)),
                ('worker_password', models.CharField(max_length=30)),
            ],
        ),
    ]
