# Generated by Django 5.1.5 on 2025-02-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_worker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_wastetype',
            new_name='tbl_category',
        ),
    ]
