# Generated by Django 5.1.5 on 2025-02-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_rename_tbl_wastetype_tbl_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_category',
            old_name='waste_type',
            new_name='category_name',
        ),
    ]
