# Generated by Django 5.1.5 on 2025-02-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_rename_waste_type_tbl_category_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_worker',
        ),
    ]
