# Generated by Django 5.1.5 on 2025-02-10 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_delete_tbl_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=30)),
                ('worker_contact', models.CharField(max_length=30)),
                ('worker_email', models.CharField(max_length=30)),
                ('worker_password', models.CharField(max_length=30)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward')),
            ],
        ),
    ]
