# Generated by Django 5.1.5 on 2025-02-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_schedule',
        ),
    ]
